// Generated by gencpp from file my_package/Corner.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_CORNER_H
#define MY_PACKAGE_MESSAGE_CORNER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_package
{
template <class ContainerAllocator>
struct Corner_
{
  typedef Corner_<ContainerAllocator> Type;

  Corner_()
    : corner_x(0.0)
    , corner_y(0.0)
    , corner_z(0.0)  {
    }
  Corner_(const ContainerAllocator& _alloc)
    : corner_x(0.0)
    , corner_y(0.0)
    , corner_z(0.0)  {
  (void)_alloc;
    }



   typedef float _corner_x_type;
  _corner_x_type corner_x;

   typedef float _corner_y_type;
  _corner_y_type corner_y;

   typedef float _corner_z_type;
  _corner_z_type corner_z;





  typedef boost::shared_ptr< ::my_package::Corner_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_package::Corner_<ContainerAllocator> const> ConstPtr;

}; // struct Corner_

typedef ::my_package::Corner_<std::allocator<void> > Corner;

typedef boost::shared_ptr< ::my_package::Corner > CornerPtr;
typedef boost::shared_ptr< ::my_package::Corner const> CornerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_package::Corner_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_package::Corner_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_package::Corner_<ContainerAllocator1> & lhs, const ::my_package::Corner_<ContainerAllocator2> & rhs)
{
  return lhs.corner_x == rhs.corner_x &&
    lhs.corner_y == rhs.corner_y &&
    lhs.corner_z == rhs.corner_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_package::Corner_<ContainerAllocator1> & lhs, const ::my_package::Corner_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_package::Corner_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_package::Corner_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::Corner_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::Corner_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::Corner_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::Corner_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_package::Corner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92060748d9174f56becd0c34fba143e6";
  }

  static const char* value(const ::my_package::Corner_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92060748d9174f56ULL;
  static const uint64_t static_value2 = 0xbecd0c34fba143e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_package::Corner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_package/Corner";
  }

  static const char* value(const ::my_package::Corner_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_package::Corner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 corner_x\n"
"float32 corner_y\n"
"float32 corner_z\n"
;
  }

  static const char* value(const ::my_package::Corner_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_package::Corner_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.corner_x);
      stream.next(m.corner_y);
      stream.next(m.corner_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Corner_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_package::Corner_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_package::Corner_<ContainerAllocator>& v)
  {
    s << indent << "corner_x: ";
    Printer<float>::stream(s, indent + "  ", v.corner_x);
    s << indent << "corner_y: ";
    Printer<float>::stream(s, indent + "  ", v.corner_y);
    s << indent << "corner_z: ";
    Printer<float>::stream(s, indent + "  ", v.corner_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_CORNER_H
